# Generated by Django 5.1.2 on 2024-10-10 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='bebida',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
