# Generated by Django 5.1.2 on 2024-10-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cancha', '0003_rename_fecha_reserva_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='cantidad_stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fecha',
        ),
        migrations.AddField(
            model_name='bebida',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bebidas_stock', to='cancha.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='cancha.bebida'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cancha.cancha'),
        ),
    ]
