# Generated by Django 5.1.2 on 2024-10-10 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0004_cancha_rename_customuser_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cancha.usuario'),
        ),
    ]
